<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE efemerides [
      <!ELEMENT efemerides (efemeride*)>
      <!ELEMENT efemeride (fecha, hecho)>
      <!ELEMENT fecha (#PCDATA)>
      <!ELEMENT hecho (#PCDATA)>
    ]>
    <efemerides>
      <efemeride>
        <fecha>20 de julio de 1969</fecha>
        <hecho>hombre en la Luna</hecho>
      </efemeride>
<efemeride> 
  <fecha>12 de octubre de 1492</fecha>
  <hecho>Llega Colón a América</hecho>
 </efemeride>
 <efemeride>
   <fecha>6 de abril de 1909</fecha>
   <hecho>Robert Peary en Polo N</hecho>
 </efemeride>
 </efemerides>
